### ISSUE TITLE
pre-computed MNIST c-scores

### ISSUE THREAD

**Issue by arturandre** [pluskid/structural-regularity#1]
Hi, I would like to ask if you could upload the pre-computed c-scores for the MNIST dataset. I could find the cifar10/100 and imagenet ones, and I'm having difficulties running JAX under windows (even with WSL).

Best regards,
Artur

**Comment by pluskid** [comment]
Maybe you can try to run it with free [Google Colab](https://colab.research.google.com/)? It should have kernels that support JAX.

**Comment by arturandre** [comment]
Thanks for the answer. 

It worked, but I had to replace `jax.experimental` with `jax.example_libraries`. And it would not detect the GPUs.

Best regards,
Artur

**Comment by pluskid** [comment]
Just FYI: we now also included pre-computed MNIST cscores in the repo.
